version: '3.7'

services:
  master1:
    image: an2071497/hadoopimg:1.13
    container_name: master1

    environment:
      - isMaster=yes

    hostname: master1
    restart: always

    networks:
      - cluster_net

    ports:
      - "9879:9870"
      - "8078:8088"
      - "8042:8042"

    volumes:
      - ./shared:/shared
      - ./shared/master_entrypoint/entrypoint.sh:/entrypoint.sh
      - ./shared/logs/masters/master1_logs:/usr/local/hadoop/logs
    

  master2:
    image: an2071497/hadoopimg:1.13
    container_name: master2
    environment:
      - isMaster=yes

    hostname: master2
    restart: always
    
    networks:
      - cluster_net

    ports:
      - "9880:9870"
      - "8079:8088"
      - "8043:8042"

    volumes:
      - ./shared:/shared
      - ./shared/master_entrypoint/entrypoint.sh:/entrypoint.sh
      - ./shared/logs/masters/master2_logs:/usr/local/hadoop/logs

  master3:
    image: an2071497/hadoopimg:1.13
    
    container_name: master3
    
    environment:
      - isMaster=yes

    hostname: master3
    restart: always

    ports:
      - "9881:9870"
      - "8080:8088"
      - "8044:8042"

    volumes:
      - ./shared:/shared
      - ./shared/master_entrypoint/entrypoint.sh:/entrypoint.sh
      - ./shared/logs/masters/master3_logs:/usr/local/hadoop/logs

    networks:
      - cluster_net


  worker:
    image: an2071497/hadoopimg:1.13

    environment:
      - isMaster=no

    restart: always

    volumes:
      - ./shared:/shared
      - ./shared/worker_entrypoint/entrypoint.sh:/entrypoint.sh
      - ./shared/logs/workers/worker1_logs:/usr/local/hadoop/logs

    networks:
      - cluster_net
    depends_on:
      - master1
      - master2
      - master3

networks:
  cluster_net:
    driver: bridge
