version: '3.7'

services:
  master1:
    image: an2071497/hadoopimg:1.15
    container_name: master1

    environment:
      - isMaster=yes

    hostname: master1
    restart: always
    
    networks:
      - cluster_net

    ports:
      - "9879:9870"
      - "8078:8088"

    volumes:
      - ./shared:/shared
      - ./shared/master_entrypoint/entrypoint.sh:/entrypoint.sh

      
    healthcheck:
      test: ["CMD-SHELL", "jps | grep -E 'QuorumPeerMain|NameNode|DFSZKFailoverController|ResourceManager|JournalNode'"]
      interval: 30s
      timeout: 10s
      retries: 3

    # mem_limit: 3G
    # cpus: 1
    depends_on:
      postgres:
        condition: service_healthy

  master2:
    image: an2071497/hadoopimg:1.15
    container_name: master2
    environment:
      - isMaster=yes

    hostname: master2
    restart: always
    
    networks:
      - cluster_net

    ports:
      - "9880:9870"
      - "8079:8088"

    volumes:
      - ./shared:/shared
      - ./shared/master_entrypoint/entrypoint.sh:/entrypoint.sh

    healthcheck:
      test: ["CMD-SHELL", "jps | grep -E 'QuorumPeerMain|NameNode|DFSZKFailoverController|ResourceManager|JournalNode'"]
      interval: 30s
      timeout: 10s
      retries: 3

    # mem_limit: 3G
    # cpus: 1
    depends_on:
      postgres:
        condition: service_healthy

  master3:
    image: an2071497/hadoopimg:1.15
    
    container_name: master3
    
    environment:
      - isMaster=yes

    hostname: master3
    restart: always

    ports:
      - "9881:9870"
      - "8080:8088"

    volumes:
      - ./shared:/shared
      - ./shared/master_entrypoint/entrypoint.sh:/entrypoint.sh

    networks:
      - cluster_net

    healthcheck:
      test: ["CMD-SHELL", "jps | grep -E 'QuorumPeerMain|NameNode|DFSZKFailoverController|ResourceManager|JournalNode'"]
      interval: 30s
      timeout: 10s
      retries: 3
    # mem_limit: 3G
    # cpus: 1
    depends_on:
      postgres:
        condition: service_healthy

  worker:
    image: an2071497/hadoopimg:1.15

    environment:
      - isMaster=no

    restart: always

    volumes:
      - ./shared:/shared
      - ./shared/worker_entrypoint/entrypoint.sh:/entrypoint.sh

    networks:
      - cluster_net

    depends_on:
      master1:
        condition: service_healthy
      master2:
        condition: service_healthy
      master3:
        condition: service_healthy

    # mem_limit: 4G
    # cpus: 3

    healthcheck:
      test: ["CMD-SHELL", "jps | grep -E 'DataNode|NodeManager'"]
      interval: 30s
      timeout: 10s
      retries: 3
  
  postgres:
    image: postgres:13
    container_name: hive-metastore
    hostname: metastore

    environment:
      POSTGRES_USER: hive_user
      POSTGRES_PASSWORD: hive_password
      POSTGRES_DB: hive
    
    ports:
      - 5432:5432
      - 5433:5433
    volumes:
      - metastoredb:/var/lib/postgresql/data
    
    networks:
      - cluster_net 
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hive_user -d hive"]
      interval: 10s
      timeout: 10s
      retries: 3
  
  # hive-lb:
  #   image: haproxy:latest
  #   container_name: hive-lb
  #   ports:
  #     - "10000:10000"
  #   volumes:
  #     - ./shared/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
  #   networks:
  #     - cluster_net
  #   depends_on:
  #     - master2
  #     - master3
  #     - worker

volumes:
  metastoredb:

networks:
  cluster_net:
    driver: bridge

# pkill -9 docker-compose; docker volume rm hha_metastoredb; rm ./shared/*.log